Volunteer Overseas/Models/Category.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Volunteer_Overseas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Category()
        {
            this.Projects = new HashSet<Project>();
        }
    
        public int id { get; set; }
        public string category_name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Project> Projects { get; set; }
    }
}

Volunteer Overseas/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PagedList;
using Volunteer_Overseas.Class;
using Volunteer_Overseas.Models;
using Volunteer_Overseas.Model;

namespace Volunteer_Overseas.Controllers
{
    public class CategoriesController : Controller
    {
        private gauravEntities db = new gauravEntities();

        // GET: Categories
        public ActionResult Category(int? pagenumber)
        {
            CategoryDataOperation category = new CategoryDataOperation();
            CategoryMetadata cCategory = new CategoryMetadata();
            //cCategory.pagination = category.GetCategoryRecord().ToPagedList(pagenumber ?? 1, 10);

            List<csp_getTypes_Result> lstCSP_getTypes_Result = category.GetCategoryRecord();
            List<CategoryMetadata> lstCustomCategoryMetadata = new List<CategoryMetadata>();

            foreach (csp_getTypes_Result csp_getTypes_Result in lstCSP_getTypes_Result)
            {
                CategoryMetadata customCategoryMetadata = new CategoryMetadata
                {
                    id = csp_getTypes_Result.Id,
                    category_name = csp_getTypes_Result.Name
                };

                lstCustomCategoryMetadata.Add(customCategoryMetadata);
            }

            return View(category.GetCategoryRecord());
        }

        // GET: Categories/Details/5
       
        // GET: Categories/Create
        public ActionResult Add()
        {
            return View();
        }

        // POST: Categories/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        //public ActionResult Add([Bind(Include = "id,category_name")] Category category)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Categories.Add(category);
        //        db.SaveChanges();
        //        return RedirectToAction("Category");
        //    }

        //    return View(category);
        //}

        // GET: Categories/Edit/5
        public ActionResult EditCategory(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Models.Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // POST: Categories/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditCategory([Bind(Include = "id,category_name")] CategoryMetadata categoryMetadata)
        {
            if (ModelState.IsValid)
            {
                Models.Category category = new Models.Category();
                category.category_name = categoryMetadata.category_name;
                //db.Entry(category).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Category");
            }
            return View(categoryMetadata);
        }

        // GET: Categories/Delete/5
        

        // POST: Categories/Delete/5

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Volunteer Overseas/Views/Categories/Add.cshtml
@{
    Layout = "~/Views/Shared/_LayoutDetail.cshtml";
}
@model Volunteer_Overseas.Models.Category
<main>
    <div class="container with-box-shadow">

        <form id="organization-detail " method="post">
            @Html.AntiForgeryToken()
            <div class="row text-center">
                <div class="col-md-12" style="font-size:40px; padding-bottom:30px">
                    Add Organization
                </div>
            </div>
            <div class="row text-center">
                <div class="col-md-6 col-md-offset-3">
                    <div class="form-group">
                        <label for="Organization Name" class="sub-header">Organization Name</label>
                        @Html.TextBoxFor(m => m.category_name, new { @class = "form-control", placeholder = "Organization Name", required = "required", @id = "Organization Name" })
                       
                    </div>
                </div>
            </div>


            <div class="text-center">
                <button class="btn btn-fill" type="submit">Add</button>
            </div>
        </form>
    </div>
</main>

Volunteer Overseas/Views/Categories/Category.cshtml
@{
    Layout = "~/Views/Shared/_LayoutDetail.cshtml";
}
@model IEnumerable<Volunteer_Overseas.Models.csp_getTypes_Result>
<main>
    <section class="admin-section">
        <div class="container">
            <div class="with-box-shadow ">
                <div class="section-title text-center">
                    <h5>Category list</h5>
                    <div class="button-outer">
                        <a class="btn btn-fill" href=@Url.Action("Add","Categories")>Add Category</a>
                        @*<button type="button" class="btn btn-fill">Add Category</button>*@
                    </div>
                </div>
                <div class="table-responsive">
                    <table class="table admin-table table-bordered table-striped">
                        <tr>
                            <th>Category name</th>
                            <th></th>
                        </tr>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@Html.DisplayFor(modelItem => item.Name)</td>
                                <td>
                                    <div class="button-outer">
                                        @Html.ActionLink("Edit", "EditCategory", new { id = item.Id }, new { @class = "btn btn-fill" })
                                        @Html.ActionLink("Delete", "DeleteCategory", new { id = item.Id }, new { @class = "btn btn-fill" })
                                    </div>
                                </td>
                            </tr>
                        }
                       
                    </table>
                </div>
                <ul class="pagination">
                    <li class="disabled">
                        <a href="#" aria-label="Previous">
                            <
                        </a>
                    </li>
                    <li class="active"><a href="#">1</a></li>
                    <li><a href="#">2</a></li>
                    <li><a href="#">3</a></li>
                    <li><a href="#">4</a></li>
                    <li class="">
                        <a href="#" aria-label="Next">
                            >
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </section>

</main>

Volunteer Overseas/Views/Categories/DeleteCategory.cshtml
@{
    Layout = "~/Views/Shared/_LayoutDetail.cshtml";
}

@model Volunteer_Overseas.Models.Category
<main>
    <div class="container with-box-shadow">

        <form id="organization-detail " method="post">
            @Html.AntiForgeryToken()
            <div class="row text-center">
                <div class="col-md-12" style="font-size:40px; padding-bottom:30px">
                   Delete Organization
                </div>
            </div>
            <div class="row text-center">
                <div class="col-md-6 col-md-offset-3">
                    <div class="form-group">
                        <label for="Organization Name" class="sub-header">Organization Name</label>
                        @*@Html.TextBoxFor(m => m.category_name, new { @class = "form-control", placeholder = "Organization Name", required = "required", @id = "Organization Name" })*@
                        @Html.EditorFor(m => m.category_name, new { htmlAttributes = new { @class = "form-control"} })
                    </div>
                </div>
            </div>


            <div class="text-center">
                <button class="btn btn-fill" type="submit">Delete</button>
            </div>
        </form>
    </div>
</main>

Volunteer Overseas/Views/Categories/EditCategory.cshtml
@{
    Layout = "~/Views/Shared/_LayoutDetail.cshtml";
}
@model Volunteer_Overseas.Model.CategoryMetadata
<main>
    <div class="container with-box-shadow">

        <form id="organization-detail " method="post">
            @Html.AntiForgeryToken()
            <div class="row text-center">
                <div class="col-md-12" style="font-size:40px; padding-bottom:30px">
                    Edit Organization
                </div>
            </div>
            <div class="row text-center">
                <div class="col-md-6 col-md-offset-3">
                    <div class="form-group">
                        <label for="Organization Name" class="sub-header">Organization Name</label>
                        @*@Html.TextBoxFor(m => m.category_name, new { @class = "form-control", placeholder = "Organization Name", required = "required", @id = "Organization Name" })*@
                        @Html.EditorFor(m => m.category_name, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>
            </div>


            <div class="text-center">
                <button class="btn btn-fill" type="submit">Save</button>
            </div>
        </form>
    </div>
</main>