Volunteer Overseas/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Volunteer_Overseas.Class;

namespace Volunteer_Overseas.Controllers
{
    public class AdminController : Controller
    {
        // GET: Admin
        public ActionResult Login()
        {
            return View();
        }
        
        public ActionResult ProjectList()
        {
            ProjectDataOperation project = new ProjectDataOperation();
            return View(project.GetProjectRecord());
        }
        public ActionResult OrganizationList()
        {
            OrganizationDataOperation organization = new OrganizationDataOperation();
            return View(organization.GetOrganizationRecords());
        }

    }
}

Volunteer Overseas/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Volunteer_Overseas.Class;
using Volunteer_Overseas.Models;

namespace Volunteer_Overseas.Controllers
{
    public class UserController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Message = "Index page";
            return View();
        }

        public ActionResult Faq()
        {
            ViewBag.Message = "Faq page";

            return View();
        }
        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";
            return View();
        }
        [HttpPost]
        public ActionResult Contact(Inquiry inquiryData)
        {
            ViewBag.Message = "Your contact page.";
            ContactDataOperation contact = new ContactDataOperation();
            if (contact.InsertContact(inquiryData))
            {
                ViewBag.status = " added sussessfully";
            }
            else
            {
                ViewBag.status = " added not sussessfully";
            }
            return View();

        }
        public ActionResult Home()
        {
            ViewBag.Message = "Home page";
            return View();
        }
        public ActionResult Search()
        {
            ViewBag.Message = "Search page";
            return View();
        }
        public ActionResult Work()
        {
            ViewBag.Message = "Work page";
            return View();
        }
    }
}

Volunteer Overseas/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Message</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet" />
    <link href="~/Content/header.css?ts=<?=time()?>" rel="stylesheet" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/owl.carousel.min.css" rel="stylesheet" />
    <link href="~/Content/owl.theme.default.min.css" rel="stylesheet" />
    <link href="~/Content/dropkick.css" rel="stylesheet" />
    <link href="~/Content/jquery-ui.min.css" rel="stylesheet" />
    <link href="~/Content/swiper.min.css" rel="stylesheet" />
    @Scripts.Render("~/bundles/modernizr")
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="~/Scripts/Header.js"></script>
</head>
<body>
    @*<div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("About", "About", "Home")</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    </ul>
                </div>
            </div>
        </div>*@
    <div class="container-fluid fixed-top header">
        <nav class="navbar navbar-expand-lg navbar-expand-md header-navbar ml-md-4 mr-md-4 py-3">
            <a href=@Url.Action("Home","User") class="logo-margin">
                <img src="../Images/logo_1.png" class="banner-logo" />
            </a>
            <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <i class="fa fa-bars fa-white"></i>
            </button>

            <div class="navbar-collapse collapse header-link" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto navbar-ul">
                    <li class="nav-item pr-5">
                        <a class="nav-link text-uppercase text-white" href=@Url.Action("Work","User")>how it works</a>
                    </li>
                    <li class="nav-item pr-5">
                        <a class="nav-link text-uppercase text-white" href=@Url.Action("Contact","User")>contact us</a>
                    </li>
                </ul>
                <form class="form-inline my-2 my-lg-0 login-form ">
                    <a href=@Url.Action("Login","Admin") class="text-white nav-link"> Login</a>
                </form>
            </div>

        </nav>
    </div>
    @RenderBody()
    <footer class="footer">
        <div class="container-fluid page-footer">
            <div class="ml-md-4 mr-md-4 py-lg-4 py-4 text-center"><img src="../Images/logo_1.png" class="footer-logo" /></div>
            <div class="footer-content py-md-4 py-sm-0">
                <div>
                    <a href=@Url.Action("Contact","User")>CONTACT US</a>
                </div>
                <div>
                    <a href=@Url.Action("Faq","User")>FAQ</a>
                </div>
            </div>
        </div>
    </footer>
</body>
</html>

Volunteer Overseas/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
    <link rel="shortcut icon" href="~/Images/favicon.ico" />
    <link href="~/admin_panel/css/main.css" rel="stylesheet" />
    <script src="~/Scripts/main.js"></script>
</head>
<body>
    <div class="wrapper admin-wrapper admin-login">
        <header>
            <div class="row header-row">
                <div class="col-lg-2 col-sm-3 col-xs-6 logo-outer">

                    <a href="index.html" title="Volunteer Overseas" class="logo"><img src="../Images/logo_1.png" alt=""><img class="color-logo" src="../Images/logo.png" alt=""></a>
                </div>
                <div class="col-lg-10 col-sm-9 col-xs-6 menu-wrap">
                    <nav>
                        <ul>
                            <li><a href="#" title="Organization">Organization</a></li>
                            <li><a href="#" title="Projects">Projects</a></li>
                            <li><a href="#" title="Application">Application</a></li>
                            <li><a href="#" title="FAQ">FAQ</a></li>
                            <li class="right-block">
                                <a href=@Url.Action("login","Admin") class="btn" title="Login">Logout</a>
                            </li>
                        </ul>
                    </nav>
                </div>
            </div>
            <a href="#" title="" class="hamburger-icon"><span></span></a>
        </header>
        @RenderBody()
    </div>
</body>
</html>

Volunteer Overseas/Views/Shared/_LayoutDetail.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
    <link rel="shortcut icon" href="~/Images/favicon.ico" />
    <link href="~/admin_panel/css/main.css" rel="stylesheet" />
    <script src="~/Scripts/main.js"></script>
</head>
<body>
    @*<div class="container-fluid shadow-sm">
            <nav class="navbar navbar-expand-lg">
                <img src="~/Images/logo.png" class="banner-logo" />
                <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <i class="fa fa-bars fa-black"></i>
                </button>

                <div class="navbar-collapse collapse header-link" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto navbar-ul">
                        <li class="nav-item pr-5">
                            <a class="nav-link text-uppercase" href="#">Organization</a>
                        </li>
                        <li class="nav-item pr-5">
                            <a class="nav-link text-uppercase" href="#">projects</a>
                        </li>
                        <li class="nav-item pr-5">
                            <a class="nav-link text-uppercase" href="#">users</a>
                        </li>
                        <li class="nav-item pr-5">
                            <a class="nav-link text-uppercase" href="#">categories</a>
                        </li>
                        <li class="nav-item pr-5">
                            <a class="nav-link text-uppercase" href="#">activities</a>
                        </li>
                        <li class="nav-item pr-5">
                            <a class="nav-link text-uppercase" href="#">faq</a>
                        </li>
                        <li class="nav-item pr-5">
                            <a class="nav-link text-uppercase" href="#">applications</a>
                        </li>
                        <li class="nav-item pr-5">
                            <a class="nav-link text-uppercase" href="#">contact inquries</a>
                        </li>
                    </ul>
                    <div class="mr-5">
                        <div>gaurav.rangapariya@internal.mail</div>
                        <div>Currently loggin as : Organization</div>
                    </div>
                    <form class="form-inline my-2 my-lg-0">
                        <button class="btn my-2 my-sm-0 btn-login">Logout</button>
                    </form>
                </div>
            </nav>

        </div>*@
    <div class="wrapper admin-wrapper admin-login">
        <header>
            <div class="row header-row">
                <div class="col-lg-2 col-sm-3 col-xs-6 logo-outer">

                    <a href="index.html" title="Volunteer Overseas" class="logo"><img src="../Images/logo_1.png" alt=""><img class="color-logo" src="../Images/logo.png" alt=""></a>
                </div>
                <div class="col-lg-10 col-sm-9 col-xs-6 menu-wrap">
                    <nav>
                        <ul>
                            <li><a href=@Url.Action("Organization","Admin") title="Organization">Organization</a></li>
                            <li><a href="#" title="Projects">Projects</a></li>
                            <li><a href="#" title="Application">users</a></li>
                            <li><a href=@Url.Action("Category","Admin") title="Category">categories</a></li>
                            <li><a href="#" title="FAQ">activities</a></li>
                            <li><a href="#" title="FAQ">faq</a></li>
                            <li><a href="#" title="FAQ">applications</a></li>
                            <li><a href="#" title="FAQ">contact inquries</a></li>
                            <li class="mr-5">
                                <div>gaurav.rangapariya@internal.mail</div>
                                <div>Currently loggin as : Organization</div>
                            </li>
                            <li class="right-block">
                                <a href=@Url.Action("login","Admin") class="btn" title="Login">Logout</a>
                            </li>
                        </ul>

                    </nav>
                </div>
            </div>
            <a href="#" title="" class="hamburger-icon"><span></span></a>
        </header>
        @RenderBody()
    </div>
    
</body>
</html>